version: 2
updates:
  - package-ecosystem: "cargo"
    # Look for `Cargo.toml` and `Cargo.lock` in the root directory
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      Rust dependencies:
        update-types: [patch, minor]

  - package-ecosystem: "github-actions"
    directory: "/"
    # Check for updates every Monday
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10

  - package-ecosystem: "npm"
    directory: "/tools/journalint-vscode"
    # Check for updates every Monday
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    groups:
      NPM dependencies:
        update-types: [patch, minor]
        exclude-patterns: ["@types/vscode"]
