.shared_windows_runners:
  tags:
    - shared-windows
    - windows-1809

stages:
  - build_crates
  - build_vsix
  - test

default:
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days

build-crates-linux:
  stage: build_crates
  image: rust:latest
  variables:
    rust_target: "x86_64-unknown-linux-gnu"
  script:
    - rustc --version
    - cargo build --release --target $rust_target
    - mkdir -p dist/$rust_target
  artifacts:
    paths:
      - "target/$rust_target/release/journalint"

build-crates-windows:
  stage: build_crates
  extends:
    - .shared_windows_runners
  variables:
    rust_target: "x86_64-pc-windows-msvc"
  script:
    - Invoke-WebRequest -OutFile rustup-init.exe https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
    - ./rustup-init.exe -y --target $rust_target
    - $env:PATH="$env:USERPROFILE\.cargo\bin;$env:PATH"
    - cargo build --release --target $rust_target
    - New-Item -ItemType Directory -Force dist/$rust_target
  artifacts:
    paths:
      - "target/$rust_target/release/journalint.exe"

build-vsix-linux:
  stage: build_vsix
  image: node:lts
  variables:
    node_target: "linux-x64"
    rust_target: "x86_64-unknown-linux-gnu"
  script:
    - node --version
    - ls -lF target/$rust_target/release
    - npm install -g @vscode/vsce
    - (cd tools/journalint-vscode; npm ci)
    - (cd tools/journalint-vscode; vsce package --target ${node_target})
    - mkdir -p dist
  artifacts:
    paths:
      - "tools/journalint-vscode/*.vsix"

build-vsix-windows:
  stage: build_vsix
  extends:
    - .shared_windows_runners
  variables:
    node_target: "win32-x64"
    rust_target: "x86_64-pc-windows-msvc"
  script:
    - node --version
    - Get-ChildItem target/$rust_target/release
    - npm install -g @vscode/vsce
    - cd tools/journalint-vscode && npm ci
    - cd tools/journalint-vscode && vsce package --target ${node_target}
    - New-Item -ItemType Directory -Force dist
  artifacts:
    paths:
      - "tools/journalint-vscode/*.vsix"

test-crates:
  stage: test
  image: rust:latest
  script:
    - cargo test
