.shared_windows_runners:
  tags:
    - shared-windows
    - windows-1809

default:
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days

cargo-fmt:
  stage: test
  image: rust:latest
  script:
    - rustup component add clippy rustfmt
    - cargo fmt --all --check
    - cargo clippy -- -D warnings

build-crates-linux:
  stage: build
  image: rust:latest
  script:
    - cargo build --release
  artifacts:
    paths:
      - "target/release/journalint"

build-crates-windows:
  stage: build
  extends:
    - .shared_windows_runners
  script:
    - Invoke-WebRequest -OutFile rustup-init.exe
                        https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
    - ./rustup-init.exe -y --target stable
    - $env:PATH="$env:USERPROFILE\.cargo\bin;$env:PATH"
    - cargo build --release
  artifacts:
    paths:
      - "target/release/journalint.exe"

build-vsix:
  stage: build
  image: node:lts
  script:
    - (cd tools/journalint-vscode; npm ci)
    - (cd tools/journalint-vscode; npm exec -- vsce package)
  artifacts:
    paths:
      - "tools/journalint-vscode/journalint-*.vsix"

test-crates:
  stage: test
  image: rust:latest
  script:
    - cargo test

# (Because the project is not Web extension, testing require a desktop environment.)
# test-vsix:
#   stage: test
#   image: node:lts
#   script:
#     - (cd tools/journalint-vscode; npm ci)
#     - (cd tools/journalint-vscode; npm run test)
