.shared_windows_runners:
  tags:
    - shared-windows
    - windows-1809

stages:
  - test
  - build_crates
  - build_vsix

default:
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days

# -----------------------------------------------------------------------------

test-crates:
  stage: test
  image: rust:latest
  script:
    - cargo test

# -----------------------------------------------------------------------------

build-crates-linux:
  stage: build_crates
  image: rust:latest
  variables:
    rust_target: "x86_64-unknown-linux-gnu"
  script:
    - rustc --version
    - cargo build --release --target $rust_target
  artifacts:
    paths:
      - "target/$rust_target/release/journalint"

build-crates-windows:
  stage: build_crates
  extends:
    - .shared_windows_runners
  variables:
    rust_target: "x86_64-pc-windows-msvc"
  script:
    - Invoke-WebRequest -OutFile rustup-init.exe https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
    - ./rustup-init.exe -y --target $rust_target
    - $env:PATH="$env:USERPROFILE\.cargo\bin;$env:PATH"
    - cargo build --release --target $rust_target
  artifacts:
    paths:
      - "target/$rust_target/release/journalint.exe"

build-vsix-linux:
  stage: build_vsix
  image: node:lts
  variables:
    node_target: "linux-x64"
    rust_target: "x86_64-unknown-linux-gnu"
  script:
    - npm install -g @vscode/vsce
    - scripts/build-vsix.sh
  artifacts:
    paths:
      - "tools/journalint-vscode/*.vsix"

build-vsix-windows:
  stage: build_vsix
  extends:
    - .shared_windows_runners
  variables:
    node_target: "win32-x64"
    rust_target: "x86_64-pc-windows-msvc"
  script:
    - Import-Module $env:ChocolateyInstall\helpers\chocolateyProfile.psm1
    - choco install nodejs-lts -y
    - refreshenv
    - "'node', 'npm' | Get-Command"
    - New-Item -Type Directory -Force $env:AppData\npm
    - npm install -g @vscode/vsce
    - scripts/build-vsix.ps1
  artifacts:
    paths:
      - "tools/journalint-vscode/*.vsix"
