.shared_windows_runners:
  tags:
    - shared-windows
    - windows-1809

default:
  artifacts:
    untracked: false
    when: on_success
    expire_in: 30 days

build-crates-linux:
  stage: build
  image: rust:latest
  parallel:
    matrix:
      - {target: "x86_64-unknown-linux-gnu" }
  script:
    - cargo build --release --target $target
    - mkdir -p dist/$target
    - mv target/$target/release/journalint dist/$target/
  artifacts:
    paths:
      - "dist/$target/journalint"

build-crates-windows:
  stage: build
  extends:
    - .shared_windows_runners
  parallel:
    matrix:
      - {target: "x86_64-pc-windows-msvc" }
  script:
    - Invoke-WebRequest -OutFile rustup-init.exe https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe
    - ./rustup-init.exe -y --target $target
    - $env:PATH="$env:USERPROFILE\.cargo\bin;$env:PATH"
    - cargo build --release --target $target
    - New-Item -ItemType Directory -Force dist/$target
    - Move-Item target/$target/release/journalint.exe dist/$target
  artifacts:
    paths:
      - "dist/$target/journalint"

build-vsix:
  stage: build
  image: node:lts
  script:
    - (cd tools/journalint-vscode; npm ci)
    - (cd tools/journalint-vscode; npm exec -- vsce package)
    - mkdir -p dist
    - mv tools/journalint-vscode/*.vsix dist
  artifacts:
    paths:
      - "dist/*.vsix"

test-crates:
  stage: test
  image: rust:latest
  script:
    - cargo test

# (Because the project is not Web extension, testing require a desktop environment.)
# test-vsix:
#   stage: test
#   image: node:lts
#   script:
#     - (cd tools/journalint-vscode; npm ci)
#     - (cd tools/journalint-vscode; npm run test)
