version: "3"

vars:
  RUST_TARGET:
    sh: rustc -vV | grep host | cut -d' ' -f 2
  NODE_TARGET:
    sh: node -p "process.platform + '-' + process.arch"

tasks:
  coverage:
    cmds:
      - cargo tarpaulin

  clean-crates:
    internal: true
    cmds:
      - cargo clean

  clean-vsix:
    internal: true
    cmds:
      - rm -rf tools/journalint-vscode/bundles
      - rm -rf tools/journalint-vscode/out
      - rm -rf tools/journalint-vscode/node_modules
      - rm -rf tools/journalint-vscode/journalint*.vsix

  clean:
    deps:
      - clean-crates
      - clean-vsix

  build-crates:
    internal: true
    cmds:
      - rustc --version
      - cargo build --release --target {{.RUST_TARGET}}

  build-vsix:
    internal: true
    cmds:
      - sh ./scripts/build-vsix.sh

  build:
    # Intentionally uses cmds instead of deps to keep build log clean
    cmds:
      - task: build-crates
      - task: build-vsix
