[package]
name = "journalint"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.23"
clap = { version = "4.1.8", features = ["derive"] }
exitcode = "1.1.2"
lazy_static = "1.4.0"
lsp-server = "0.7.0"
lsp-types = "0.94.0"
regex = "1.7.1"
serde_json = "1.0.94"
thiserror = "1.0.39"
