[package]
name = "journalint-parse"
version.workspace = true
edition.workspace = true

[dependencies]
chrono.workspace = true
chumsky.workspace = true
serde.workspace = true
thiserror.workspace = true
url.workspace = true

[dev-dependencies]
rstest.workspace = true
