name: "CI/CD"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    name: ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # prettier-ignore
          - { target: x86_64-pc-windows-msvc,   os: windows-2019, suffix: ".exe" }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-20.04, suffix: ""     }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - name: Build
        id: build
        run: cargo build --release --target=${{ matrix.job.target }}

      - name: Archive
        run: tar -cvfJ journalint-${{ matrix.job.target }}.tar.xz target/${{ matrix.job.target }}/release/journalint{{ matrix.job.suffix }}

      - name: Upload artifact
        uses: actions/upload-artifact@master
        with:
          path: journalint-*.tar.xz
