name: "CI/CD"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  # Build both journalint and journalint-vscode.
  build:
    name: ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    env:
      DISPLAY: ":99"
    strategy:
      fail-fast: false
      matrix:
        job:
          # prettier-ignore
          - { target: x86_64-pc-windows-msvc,   os: windows-latest, script: dist.ps1 }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest,  script: dist.sh  }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install and start xvfb (for Linux GUI testing)
        if: ${{ matrix.job.os == 'ubuntu-latest' }}
        run: |
          sudo apt-get update
          sudo apt-get install -y xvfb
          Xvfb :99 -screen 0 1024x768x24 &

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - name: Install Node.js toolchain
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install yarn and vsce globally
        run: |
          npm install -g yarn
          npm install -g @vscode/vsce

      - name: Test native code
        run: cargo test --target ${{ matrix.job.target }}

      - name: Test VSCode extension
        run: (cd tools/journalint-vscode && npm ci && npm run test)

      - name: Build
        run: |
          scripts/${{ matrix.job.script }}
          ls dist

      # Upload the executable file and the VSIX file
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.job.target }}
          path: dist/*

  # Create a release for a newly pushed tag.
  release:
    needs: [build]
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}
    permissions:
      contents: write
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: artifacts/
      - run: "gh release create ${{ github.ref_name }} artifacts/*/*"
