name: "CI/CD"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "*"

jobs:
  build:
    name: ${{ matrix.job.target }}
    runs-on: ${{ matrix.job.os }}
    strategy:
      fail-fast: false
      matrix:
        job:
          # prettier-ignore
          - { target: x86_64-pc-windows-msvc,   os: windows-latest, script: makedist.ps1 }
          - { target: x86_64-unknown-linux-gnu, os: ubuntu-latest,  script: makedist.sh  }
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.job.target }}

      - name: Install Node.js toolchain
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install vsce command globally
        run: npm install -g @vscode/vsce

      - name: Build
        run: |
          scripts/${{ matrix.job.script }}
          ls dist

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: artifacts-${{ matrix.job.target }}
          path: dist/*
